kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vm-cirros-pvc1
  annotations:
    k8s.io/CloneRequest: cirros
spec:
  storageClassName: standalone-cinder
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vm-cirros-pvc2
  annotations:
    k8s.io/CloneRequest: cirros
spec:
  storageClassName: standalone-cinder
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
